import type { Kennel } from "../types";

export const mockKennels: Kennel[] = [
  {
    currentOccupantId: "1",
    features: ["heated", "covered"],
    gridX: 0,
    gridY: 0,
    id: "K1",
    lastCleanedAt: new Date("2024-02-20T08:00:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 1",
    notes: "Regular cleaning needed",
    size: "medium",
    status: "occupied",
    type: "standard",
  },
  {
    currentOccupantId: "2",
    features: ["heated", "covered"],
    gridX: 1,
    gridY: 0,
    id: "K2",
    lastCleanedAt: new Date("2024-02-20T08:15:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 2",
    notes: "",
    size: "medium",
    status: "occupied",
    type: "standard",
  },
  {
    currentOccupantId: "3",
    features: ["heated", "covered", "sound-proof"],
    gridX: 0,
    gridY: 1,
    id: "K3",
    lastCleanedAt: new Date("2024-02-20T08:30:00Z"),
    location: "Building B",
    maintenanceNotes: [
      {
        createdAt: new Date("2024-02-20T08:30:00Z"),
        notes: "Door hinge needs fixing",
      },
    ],
    maintenanceStatus: "needs-repair",
    name: "Kennel 3",
    notes: "Used for reactive dogs",
    size: "large",
    status: "occupied",
    type: "isolation",
  },
  {
    currentOccupantId: "4",
    features: ["heated", "covered", "extra-padding"],
    gridX: 1,
    gridY: 1,
    id: "K4",
    lastCleanedAt: new Date("2024-02-20T08:45:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 4",
    notes: "Modified for senior dogs",
    size: "medium",
    status: "occupied",
    type: "senior",
  },
  {
    currentOccupantId: "5",
    features: ["heated", "covered"],
    gridX: 0,
    gridY: 2,
    id: "K5",
    lastCleanedAt: new Date("2024-02-20T09:00:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 5",
    notes: "",
    size: "medium",
    status: "occupied",
    type: "standard",
  },
  {
    currentOccupantId: "6",
    features: ["heated", "covered"],
    gridX: 1,
    gridY: 2,
    id: "K6",
    lastCleanedAt: new Date("2024-02-20T09:15:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 6",
    notes: "",
    size: "medium",
    status: "occupied",
    type: "standard",
  },
  {
    currentOccupantId: "7",
    features: ["heated", "covered", "reinforced"],
    gridX: 0,
    gridY: 3,
    id: "K7",
    lastCleanedAt: new Date("2024-02-20T09:30:00Z"),
    location: "Building B",
    maintenanceStatus: "good",
    name: "Kennel 7",
    notes: "Strong door for powerful dogs",
    size: "large",
    status: "occupied",
    type: "isolation",
  },
  {
    currentOccupantId: "8",
    features: ["heated", "covered", "sound-dampening"],
    gridX: 1,
    gridY: 3,
    id: "K8",
    lastCleanedAt: new Date("2024-02-20T09:45:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 8",
    notes: "Quieter area for shy dogs",
    size: "medium",
    status: "occupied",
    type: "quiet",
  },
  {
    currentOccupantId: "9",
    features: ["heated", "covered", "sound-proof"],
    gridX: 0,
    gridY: 4,
    id: "K9",
    lastCleanedAt: new Date("2024-02-20T10:00:00Z"),
    location: "Building B",
    maintenanceStatus: "good",
    name: "Kennel 9",
    notes: "Used for reactive dogs",
    size: "large",
    status: "occupied",
    type: "isolation",
  },
  {
    currentOccupantId: "10",
    features: ["heated", "covered"],
    gridX: 1,
    gridY: 4,
    id: "K10",
    lastCleanedAt: new Date("2024-02-20T10:15:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 10",
    notes: "",
    size: "medium",
    status: "occupied",
    type: "standard",
  },
  {
    currentOccupantId: "11",
    features: ["heated", "covered"],
    gridX: 0,
    gridY: 5,
    id: "K11",
    lastCleanedAt: new Date("2024-02-20T10:30:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 11",
    notes: "",
    size: "medium",
    status: "occupied",
    type: "standard",
  },
  {
    currentOccupantId: "12",
    features: ["heated", "covered"],
    gridX: 1,
    gridY: 5,
    id: "K12",
    lastCleanedAt: new Date("2024-02-20T10:45:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 12",
    notes: "",
    size: "medium",
    status: "occupied",
    type: "standard",
  },
  {
    currentOccupantId: "13",
    features: ["heated", "covered", "sound-proof"],
    gridX: 0,
    gridY: 6,
    id: "K13",
    lastCleanedAt: new Date("2024-02-20T11:00:00Z"),
    location: "Building B",
    maintenanceStatus: "good",
    name: "Kennel 13",
    notes: "Used for reactive dogs",
    size: "large",
    status: "occupied",
    type: "isolation",
  },
  {
    currentOccupantId: "14",
    features: ["heated", "covered", "extra-padding"],
    gridX: 1,
    gridY: 6,
    id: "K14",
    lastCleanedAt: new Date("2024-02-20T11:15:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 14",
    notes: "",
    size: "medium",
    status: "occupied",
    type: "standard",
  },
  {
    currentOccupantId: "15",
    features: ["heated", "covered", "extra-padding"],
    gridX: 0,
    gridY: 7,
    id: "K15",
    lastCleanedAt: new Date("2024-02-20T11:30:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 15",
    notes: "Modified for senior dogs",
    size: "medium",
    status: "occupied",
    type: "senior",
  },
  {
    currentOccupantId: null,
    features: ["heated", "covered"],
    gridX: 1,
    gridY: 7,
    id: "K16",
    lastCleanedAt: new Date("2024-02-20T11:45:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 16",
    notes: "",
    size: "small",
    status: "available",
    type: "standard",
  },
  {
    currentOccupantId: null,
    features: ["heated", "covered", "sound-dampening"],
    gridX: 0,
    gridY: 8,
    id: "K17",
    lastCleanedAt: new Date("2024-02-20T12:00:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 17",
    notes: "Quieter area",
    size: "medium",
    status: "available",
    type: "quiet",
  },
  {
    currentOccupantId: null,
    features: ["heated", "covered"],
    gridX: 1,
    gridY: 8,
    id: "K18",
    lastCleanedAt: new Date("2024-02-20T12:15:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 18",
    notes: "",
    size: "large",
    status: "available",
    type: "standard",
  },
  {
    currentOccupantId: null,
    features: ["heated", "covered", "reinforced"],
    gridX: 0,
    gridY: 9,
    id: "K19",
    lastCleanedAt: new Date("2024-02-20T12:30:00Z"),
    location: "Building B",
    maintenanceStatus: "good",
    name: "Kennel 19",
    notes: "Strong door for powerful dogs",
    size: "large",
    status: "available",
    type: "isolation",
  },
  {
    currentOccupantId: null,
    features: ["heated", "covered"],
    gridX: 1,
    gridY: 9,
    id: "K20",
    lastCleanedAt: new Date("2024-02-20T12:45:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 20",
    notes: "",
    size: "medium",
    status: "available",
    type: "standard",
  },
  {
    currentOccupantId: null,
    features: ["heated", "covered", "extra-padding"],
    gridX: 0,
    gridY: 10,
    id: "K21",
    lastCleanedAt: new Date("2024-02-20T13:00:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 21",
    notes: "",
    size: "medium",
    status: "available",
    type: "senior",
  },
  {
    currentOccupantId: null,
    features: ["heated", "covered"],
    gridX: 1,
    gridY: 10,
    id: "K22",
    lastCleanedAt: new Date("2024-02-20T13:15:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 22",
    notes: "",
    size: "small",
    status: "available",
    type: "standard",
  },
  {
    currentOccupantId: null,
    features: ["heated", "covered", "sound-proof"],
    gridX: 0,
    gridY: 11,
    id: "K23",
    lastCleanedAt: new Date("2024-02-20T13:30:00Z"),
    location: "Building B",
    maintenanceStatus: "good",
    name: "Kennel 23",
    notes: "Used for reactive dogs",
    size: "large",
    status: "available",
    type: "isolation",
  },
  {
    currentOccupantId: null,
    features: ["heated", "covered"],
    gridX: 1,
    gridY: 11,
    id: "K24",
    lastCleanedAt: new Date("2024-02-20T13:45:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 24",
    notes: "",
    size: "medium",
    status: "available",
    type: "standard",
  },
  {
    currentOccupantId: null,
    features: ["heated", "covered", "sound-dampening"],
    gridX: 0,
    gridY: 12,
    id: "K25",
    lastCleanedAt: new Date("2024-02-20T14:00:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 25",
    notes: "Quieter area",
    size: "medium",
    status: "available",
    type: "quiet",
  },
  {
    currentOccupantId: null,
    features: ["heated", "covered"],
    gridX: 1,
    gridY: 12,
    id: "K26",
    lastCleanedAt: new Date("2024-02-20T14:15:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 26",
    notes: "",
    size: "large",
    status: "available",
    type: "standard",
  },
  {
    currentOccupantId: null,
    features: ["heated", "covered", "extra-padding"],
    gridX: 0,
    gridY: 13,
    id: "K27",
    lastCleanedAt: new Date("2024-02-20T14:30:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 27",
    notes: "Modified for senior dogs",
    size: "medium",
    status: "available",
    type: "senior",
  },
  {
    currentOccupantId: null,
    features: ["heated", "covered"],
    gridX: 1,
    gridY: 13,
    id: "K28",
    lastCleanedAt: new Date("2024-02-20T14:45:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 28",
    notes: "",
    size: "small",
    status: "available",
    type: "standard",
  },
  {
    currentOccupantId: null,
    features: ["heated", "covered", "reinforced"],
    gridX: 0,
    gridY: 14,
    id: "K29",
    lastCleanedAt: new Date("2024-02-20T15:00:00Z"),
    location: "Building B",
    maintenanceStatus: "good",
    name: "Kennel 29",
    notes: "Strong door for powerful dogs",
    size: "large",
    status: "available",
    type: "isolation",
  },
  {
    currentOccupantId: null,
    features: ["heated", "covered"],
    gridX: 1,
    gridY: 14,
    id: "K30",
    lastCleanedAt: new Date("2024-02-20T15:15:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 30",
    notes: "",
    size: "medium",
    status: "available",
    type: "standard",
  },
  {
    currentOccupantId: null,
    features: ["heated", "covered"],
    gridX: 0,
    gridY: 15,
    id: "K31",
    lastCleanedAt: new Date("2024-02-20T15:30:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 31",
    notes: "",
    size: "medium",
    status: "available",
    type: "standard",
  },
  {
    currentOccupantId: null,
    features: ["heated", "covered", "sound-dampening"],
    gridX: 1,
    gridY: 15,
    id: "K32",
    lastCleanedAt: new Date("2024-02-20T15:45:00Z"),
    location: "Building A",
    maintenanceStatus: "good",
    name: "Kennel 32",
    notes: "Quieter area",
    size: "medium",
    status: "available",
    type: "quiet",
  },
];
